FROM openjdk:latest
WORKDIR '/gg-deploy'
ARG ARTIFACT_NAME='dmtnt-0.0.1-SNAPSHOT.jar'
ARG ARTIFACT_PATH=target/${ARTIFACT_NAME}
COPY $ARTIFACT_PATH .
EXPOSE 9081
ENV SERVER_PORT=9081
ENTRYPOINT ["java", "-jar", "dmtnt-0.0.1-SNAPSHOT.jar"]